export const ERROR_CODE = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  OAUTH_EMAIL_REQUIRED: "OAUTH_EMAIL_REQUIRED",
  OAUTH_PROVIDER_CONFIG_MISSING: "OAUTH_PROVIDER_CONFIG_MISSING",
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
